version: '3'
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper1
    container_name: zookeeper1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 12181:2181
  zookeeper2:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper2
    container_name: zookeeper2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  zookeeper3:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper3
    container_name: zookeeper3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181

  broker1:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker1
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper1, zookeeper2, zookeeper3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:19092,PLAINTEXT://broker1:9092

  broker2:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker2
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper1, zookeeper2, zookeeper3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:29092,PLAINTEXT://broker2:9092

  broker3:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker3
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper1, zookeeper2, zookeeper3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:39092,PLAINTEXT://broker3:9092
